# Generated by Django 2.0.5 on 2018-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
