# Generated by Django 2.0.5 on 2018-06-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entry_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.CharField(default='HOSTNAME', max_length=300),
        ),
    ]
