# Generated by Django 2.0.5 on 2018-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180628_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='code',
        ),
    ]
