# Generated by Django 2.0.5 on 2018-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
