# Generated by Django 2.0.5 on 2018-06-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_entry_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
    ]
