# Generated by Django 2.0.5 on 2018-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_entry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
