# Generated by Django 2.0.5 on 2018-07-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_entry_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_server',
            old_name='client',
            new_name='server',
        ),
    ]
