# Generated by Django 2.0.5 on 2018-07-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180706_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry_server',
            new_name='EntryServer',
        ),
    ]
