# Generated by Django 2.0.5 on 2018-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180706_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryserver',
            name='ip',
            field=models.TextField(),
        ),
    ]
