# Generated by Django 2.0.5 on 2018-07-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180706_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryserver',
            options={'verbose_name_plural': 'hosts'},
        ),
    ]
