# Generated by Django 2.0.5 on 2018-07-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180706_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryserver',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
