# Generated by Django 2.0.5 on 2018-07-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_server_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryserver',
            name='server',
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': 'serverentries'},
        ),
        migrations.RemoveField(
            model_name='server',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='server',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Client'),
        ),
        migrations.DeleteModel(
            name='EntryServer',
        ),
    ]
