# Generated by Django 2.0.5 on 2018-07-12 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180711_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
