# Generated by Django 2.0.5 on 2018-07-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180718_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': 'servers'},
        ),
    ]
