# Generated by Django 2.0.5 on 2018-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180718_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
