# Generated by Django 2.0.5 on 2018-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180718_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(default='ip', max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.CharField(default='port', max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
