# Generated by Django 2.0.5 on 2018-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180724_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='check_cpu',
            field=models.CharField(default='check_cpu', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_disk',
            field=models.CharField(default='check_disk', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_logs',
            field=models.CharField(default='check_logs', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_memory',
            field=models.CharField(default='check_memory', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_uptime',
            field=models.CharField(default='check_uptime', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_was',
            field=models.CharField(default='check_was', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.CharField(default='22', max_length=200),
        ),
    ]
