# Generated by Django 2.0.5 on 2018-07-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180726_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='check_users',
            field=models.CharField(default='check_users', max_length=200),
        ),
    ]
