# Generated by Django 2.0.5 on 2018-07-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_server_check_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(default='instance_name', max_length=200)),
                ('pid', models.CharField(default='pid', max_length=200)),
                ('status', models.CharField(default='status', max_length=200)),
                ('server', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Server')),
            ],
            options={
                'verbose_name_plural': 'instances',
            },
        ),
    ]
