# Generated by Django 2.0.5 on 2018-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='instance',
        ),
        migrations.AddField(
            model_name='instance',
            name='text',
            field=models.CharField(default='instance_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='instance',
            name='pid',
            field=models.CharField(default='pid', max_length=300),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(default='status', max_length=300),
        ),
    ]
