# Generated by Django 2.0.5 on 2018-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180730_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='check_instance1',
            field=models.CharField(default='check_instance1', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance2',
            field=models.CharField(default='check_instance2', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance3',
            field=models.CharField(default='check_instance3', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance4',
            field=models.CharField(default='check_instance4', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance5',
            field=models.CharField(default='check_intance5', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance6',
            field=models.CharField(default='check_instance6', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance7',
            field=models.CharField(default='check_instance7', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='check_instance8',
            field=models.CharField(default='check_instance10', max_length=500),
        ),
    ]
